# Test this without rebuilding the docker image $> docker-compose up
# Test this with rebuilding the docker image $> docker-compose up --build

version: '3.7'

services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile-project2
    image: csci652:latest
    container_name: peer1
    working_dir: /csci652/project2
    networks:
      csci652network:
        ipv4_address: 172.16.238.2
    command:
      - /bin/bash
      - -c
      - |
        echo "Initialize server...done!"
        tail -f /dev/null


  peer2:
    image: csci652:latest
    container_name: peer2
    depends_on:
      - peer1
    working_dir: /csci652/project2
    networks:
      csci652network:
        ipv4_address: 172.16.238.3
    command:
      - /bin/bash
      - -c
      - |
        echo "Initialize PubSubAgent...done!"
        tail -f /dev/null

  peer3:
    image: csci652:latest
    container_name: peer3
    depends_on:
      - peer1
    working_dir: /csci652/project2
    networks:
      csci652network:
        ipv4_address: 172.16.238.4
    command:
      - /bin/bash
      - -c
      - |
        echo "Initialize PubSubAgent...done!"
        tail -f /dev/null

networks:
  csci652network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"